In [4]:
from pychiver.archiver import Archiver

### Easy data extraction

Follows the same concept as for the regular scalars `.get()`, however a direct use `.getWaveform()` results in warning and encapsulated data

In [7]:
archiver = Archiver(archiver_url='http://archiver-01.tn.esss.lu.se')
start = "2021-06-25 14:00:00"
end = "2021-06-25 14:30:00"
PV = "RFQ-010:RFS-Kly-110:PwrFwd-Wave-PM"
data = archiver.get(PV, start_date=start, end_date=end)

/Users/arekgorzawski/opt/anaconda3/lib/python3.8/site-packages/pychiver/archiver.py:220: UserWarning: The PV 'RFQ-010:RFS-Kly-110:PwrFwd-Wave-PM' you have extracted is type of WAVEFORM with 8000 samples
  if waveform_alert: warnings.warn("The PV \'{}\' you have extracted is type of WAVEFORM with {} samples".

In [12]:
data[PV].head(3)

,secs,val,nanos,severity,status,status_label,severity_label,secs_nanos,time
0,1624629600,"[6.508574478139793, 6.506821798867371, 6.51120...",351034382,0,0,EpicsStatus.NO_ALARM,EpicsSeverity.NO_ALARM,1.624630e+09,2021-06-25 14:00:00.351034403
1,1624629790,"[6.511203497048426, 6.506821798867371, 6.51383...",353562190,0,0,EpicsStatus.NO_ALARM,EpicsSeverity.NO_ALARM,1.624630e+09,2021-06-25 14:03:10.353562117
2,1624629974,"[6.51383251595706, 6.515585195229482, 6.510327...",355372912,0,0,EpicsStatus.NO_ALARM,EpicsSeverity.NO_ALARM,1.624630e+09,2021-06-25 14:06:14.355372906

In [14]:
archiver = Archiver(archiver_url='http://archiver-01.tn.esss.lu.se')
pm = archiver.getWaveform(PV, start_date=start_time, end_date=end_time)

In [16]:
pm.head(3)

,secs,val,nanos,severity,status,status_label,severity_label,secs_nanos,time
0,1624629600,"[6.508574478139793, 6.506821798867371, 6.51120...",351034382,0,0,EpicsStatus.NO_ALARM,EpicsSeverity.NO_ALARM,1.624630e+09,2021-06-25 14:00:00.351034403
1,1624629790,"[6.511203497048426, 6.506821798867371, 6.51383...",353562190,0,0,EpicsStatus.NO_ALARM,EpicsSeverity.NO_ALARM,1.624630e+09,2021-06-25 14:03:10.353562117
2,1624629974,"[6.51383251595706, 6.515585195229482, 6.510327...",355372912,0,0,EpicsStatus.NO_ALARM,EpicsSeverity.NO_ALARM,1.624630e+09,2021-06-25 14:06:14.355372906